---
- name: Install Obsidian via Flatpak
  community.general.flatpak:
    name: md.obsidian.Obsidian
    state: present
    method: system

- name: Install Extension Manager via Flatpak
  community.general.flatpak:
    name: com.mattjakeman.ExtensionManager
    state: present
    method: system
